"""Update emision models

Revision ID: 70b0d18b918b
Revises: ebf888d1474f
Create Date: 2024-08-04 19:05:35.162802

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '70b0d18b918b'
down_revision = 'ebf888d1474f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
