"""Initial migration

Revision ID: 9ef738148311
Revises: 1a31ce608336
Create Date: 2024-08-04 00:02:15.372839

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '9ef738148311'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convenio',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('distribuidor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sucursal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizacionobjeto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('convenio_id', sa.Uuid(), nullable=False),
    sa.Column('sucursal_id', sa.Integer(), nullable=False),
    sa.Column('distribuidor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenio.id'], ),
    sa.ForeignKeyConstraint(['distribuidor_id'], ['distribuidor.id'], ),
    sa.ForeignKeyConstraint(['sucursal_id'], ['sucursal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_comercial', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cotizacion_objeto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_objeto_id'], ['cotizacionobjeto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detsolicitud',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('renovacion', sa.Integer(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paquete', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_nacimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ini_vig_reportada', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fin_vig_reportada', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plazo_reportado', sa.Integer(), nullable=False),
    sa.Column('tipo_vig', sa.Integer(), nullable=False),
    sa.Column('sum_aseg_4', sa.Float(), nullable=False),
    sa.Column('sum_aseg_5', sa.Float(), nullable=True),
    sa.Column('sum_aseg_6', sa.Float(), nullable=True),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cobertura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clave_cobertura', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prima', sa.Float(), nullable=False),
    sa.Column('det_solicitud_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['det_solicitud_id'], ['detsolicitud.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cobertura')
    op.drop_table('detsolicitud')
    op.drop_table('cotizacion')
    op.drop_table('cotizacionobjeto')
    op.drop_table('sucursal')
    op.drop_table('distribuidor')
    op.drop_table('convenio')
    # ### end Alembic commands ###
