"""Add emision models

Revision ID: ebf888d1474f
Revises: be9c2efb557d
Create Date: 2024-08-04 18:53:12.552009

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'ebf888d1474f'
down_revision = 'be9c2efb557d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emision',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('id_convenio', sa.Uuid(), nullable=False),
    sa.Column('suc_clave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suc_nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distribuidor_clave', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distribuidor_nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('distribuidor_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aseguradosadicionales',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parentesco', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_identificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_identificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_nacimiento', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('emision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['emision_id'], ['emision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificadodetalle',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_identificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('numero_identificacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sexo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('etiqueta_adicional1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_adicional1', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('etiqueta_adicional2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_adicional2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('etiqueta_adicional3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('data_adicional3', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('emision_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['emision_id'], ['emision.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('certificadodetalle')
    op.drop_table('aseguradosadicionales')
    op.drop_table('emision')
    # ### end Alembic commands ###
